"""set more chars

Revision ID: 611ae00a062f
Revises: 23721d3e00cc
Create Date: 2023-10-09 14:14:01.375043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '611ae00a062f'
down_revision = '23721d3e00cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('description', sa.String(length=4000), nullable=True))
    op.add_column('cities', sa.Column('description', sa.String(length=4000), nullable=True))
    op.add_column('complain_statuses', sa.Column('description', sa.String(length=4000), nullable=True))
    op.add_column('complains', sa.Column('description_ru', sa.String(length=4000), nullable=True))
    op.add_column('countries', sa.Column('description', sa.String(length=4000), nullable=True))
    op.add_column('districts', sa.Column('description', sa.String(length=4000), nullable=True))
    op.add_column('genders', sa.Column('description', sa.String(length=4000), nullable=True))
    op.add_column('regions', sa.Column('description', sa.String(length=4000), nullable=True))
    op.add_column('rights', sa.Column('description', sa.String(length=4000), nullable=True))
    op.add_column('roles', sa.Column('description', sa.String(length=4000), nullable=True))
    op.add_column('statuses', sa.Column('description', sa.String(length=4000), nullable=True))
    op.add_column('users', sa.Column('description', sa.String(length=4000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'description')
    op.drop_column('statuses', 'description')
    op.drop_column('roles', 'description')
    op.drop_column('rights', 'description')
    op.drop_column('regions', 'description')
    op.drop_column('genders', 'description')
    op.drop_column('districts', 'description')
    op.drop_column('countries', 'description')
    op.drop_column('complains', 'description_ru')
    op.drop_column('complain_statuses', 'description')
    op.drop_column('cities', 'description')
    op.drop_column('categories', 'description')
    # ### end Alembic commands ###
