"""add_RBAC

Revision ID: a3cd168fe87a
Revises: f74b65f618d3
Create Date: 2023-06-29 23:04:12.884935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3cd168fe87a'
down_revision = 'f74b65f618d3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_permission',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], )
    )
    op.add_column('permissions', sa.Column('alias', sa.String(length=255), nullable=False))
    op.alter_column('permissions', 'name_ru',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint('permissions_role_id_fkey', 'permissions', type_='foreignkey')
    op.drop_column('permissions', 'role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('permissions_role_id_fkey', 'permissions', 'roles', ['role_id'], ['id'])
    op.alter_column('permissions', 'name_ru',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('permissions', 'alias')
    op.drop_table('role_permission')
    # ### end Alembic commands ###
