"""add_phone

Revision ID: 9294ae927ff4
Revises: 24c0a741af87
Create Date: 2023-06-24 17:31:01.123263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9294ae927ff4'
down_revision = '24c0a741af87'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('phone', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments', 'phone')
    # ### end Alembic commands ###
