"""add relation to cities

Revision ID: fe91b46c2669
Revises: a3cd168fe87a
Create Date: 2023-07-05 14:08:15.303303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe91b46c2669'
down_revision = 'a3cd168fe87a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complains', sa.Column('action_date', sa.DateTime(), nullable=True))
    op.add_column('departments', sa.Column('city_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'departments', 'cities', ['city_id'], ['id'])
    op.add_column('users', sa.Column('city_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'cities', ['city_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'city_id')
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_column('departments', 'city_id')
    op.drop_column('complains', 'action_date')
    # ### end Alembic commands ###
