"""new field in complains

Revision ID: 23721d3e00cc
Revises: a3609d3a164d
Create Date: 2023-09-09 01:11:19.139598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23721d3e00cc'
down_revision = 'a3609d3a164d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complains', sa.Column('action_city_id', sa.Integer(), nullable=True))
    op.add_column('complains', sa.Column('action_district_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'complains', 'cities', ['action_city_id'], ['id'])
    op.create_foreign_key(None, 'complains', 'districts', ['action_district_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'complains', type_='foreignkey')
    op.drop_constraint(None, 'complains', type_='foreignkey')
    op.drop_column('complains', 'action_district_id')
    op.drop_column('complains', 'action_city_id')
    # ### end Alembic commands ###
