"""add_permissions

Revision ID: 24c0a741af87
Revises: 94ec2ff35856
Create Date: 2023-06-23 15:25:24.541369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24c0a741af87'
down_revision = '94ec2ff35856'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_ru', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('name_uz', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('departments', sa.Column('title_ru', sa.String(length=255), nullable=True))
    op.add_column('departments', sa.Column('title_en', sa.String(length=255), nullable=True))
    op.add_column('departments', sa.Column('title_uz', sa.String(length=255), nullable=True))
    op.add_column('departments', sa.Column('phone_number', sa.String(length=255), nullable=True))
    op.drop_column('departments', 'title')
    op.drop_column('departments', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('departments', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('departments', 'phone_number')
    op.drop_column('departments', 'title_uz')
    op.drop_column('departments', 'title_en')
    op.drop_column('departments', 'title_ru')
    op.drop_table('permissions')
    # ### end Alembic commands ###
